// @flow

export const API_URL = '/api'
export const APP_SETTINGS = `${API_URL}/settings`
export const BIRTHDATES_NEAREST_URL = `${API_URL}/birth_dates/nearest`
export const CANDIDATES_URL = `${API_URL}/candidates`
export const CANDIDATE_URL = `${CANDIDATES_URL}/{{ id }}`
export const CANDIDATE_VACANCIES = `${API_URL}/candidate_vacancies/{{ id }}/comments`
export const ACCOUNTS_URL = `${API_URL}/accounts`
export const GET_TICKET_URL = `${ACCOUNTS_URL}/get_ticket`
export const PROFILE_URL = `${ACCOUNTS_URL}/{{ id }}`
export const PROFILE_PHOTOS_URL = `${ACCOUNTS_URL}/{{ accountId }}/account_photos`
export const PROFILE_PHOTO_URL = `${ACCOUNTS_URL}/{{ accountId }}/account_photos/ {{ id }}`
export const CONFIRM_SKILL_URL = `${API_URL}/account_skills/{{ id }}/confirm`
export const UNCONFIRM_SKILL_URL = `${API_URL}/account_skills/{{ id }}/unconfirm`
export const EVENTS_URL = `${API_URL}/events`
export const DICTIONARIS_EVENT_TYPE_URL = `${API_URL}/dictionaries/event_type`
export const DICTIONARIES_ACCOUNTS_URL = `${ACCOUNTS_URL}/dictionary`
export const DICTIONARIES_PROJECTS_URL = `${API_URL}/projects/dictionary`
export const DICTIONARIES_VACANCIES_URL = `${API_URL}/vacancies/dictionary`
export const DICTIONARIES_VACANCY_STAGE_GROUP_URL = `${API_URL}/dictionaries/vacancy_stage_group`
export const DICTIONARIES_NEWS_CATEGORY_URL = `${API_URL}/dictionaries/news_category`

export const DICTIONARIES_DEPARTMENTS_URL = `${API_URL}/dictionaries/department`
export const DICTIONARIES_DEPARTMENTS_NAMES_URL = `${API_URL}/dictionaries/department_names`
export const DICTIONARIES_PROFESSIONAL_SPECIALIZATIONS_URL = `${API_URL}/dictionaries/professional_specialization`
export const DICTIONARIES_CANDIDATE_SKILLS_URL = `${API_URL}/dictionaries/candidate_skill`

export const DICTIONARIES_TAG_URL = `${API_URL}/dictionaries/tag`
export const DICTIONARIES_RESUME_SOURCES_URL = `${API_URL}/dictionaries/resume_source`
export const DICTIONARIES_LANGUAGES_URL = `${API_URL}/dictionaries/language`
export const DICTIONARIES_LANGUAGES_LEVEL_URL = `${API_URL}/dictionaries/language_level`
export const DICTIONARIES_EDUCATION_LEVEL_URL = `${API_URL}/dictionaries/education_level`
export const DICTIONARIES_SPECIALIZATION_URL = `${API_URL}/dictionaries/professional_area`
export const DICTIONARIES_OFFICES_URL = `${API_URL}/dictionaries/office`
export const DICTIONARIES_POSITIONS_URL = `${API_URL}/dictionaries/position`
export const DICTIONARIES_SKILLS_URL = `${API_URL}/dictionaries/skill`
export const DICTIONARIES_CITIES_URL = `${API_URL}/dictionaries/accounts_city`
export const DICTIONARIES_STRUCTURE_UNITS_URL = `${API_URL}/dictionaries/structure_unit`
export const DICTIONARIES_CONTACT_TYPES_URL = `${API_URL}/dictionaries/contract_type`
export const DICTIONARIES_EMPLOYEE_STATES_URL = `${API_URL}/dictionaries/employee_state`
export const EVENT_URL = `${EVENTS_URL}/{{ id }}`
export const EVENT_PARTICIPANTS = `${API_URL}/event_participants`
export const DICTIONARIES_SEARCH_SKILLS_URL = `${API_URL}/skills`
export const TEMPLATE_STAGES_URL = `${API_URL}/template_stages`
export const NEWS_URL = `${API_URL}/news`
export const NEW_URL = `${NEWS_URL}/{{ id }}`
export const PROFILE_ME_URL = `${ACCOUNTS_URL}/me`
export const PERMISSIONS_MY_URL = `${API_URL}/permissions/my`
export const SURVEYS_URL = `${API_URL}/surveys`
export const SURVEY_URL = `${SURVEYS_URL}/{{ id }}`
export const SURVEY_RESULTS_URL = `${API_URL}/survey_results`
export const VACANCIES_URL = `${API_URL}/vacancies`
export const VACANCY_URL = `${API_URL}/vacancies/{{ id }}`
export const VACANCY_STAGES_URL = `${API_URL}/vacancies/{{ id }}/vacancy_stages`
export const VACANCY_CANDIDATES_URL = `${API_URL}/vacancies/{{ id }}/candidates`
export const VACANCY_CANDIDATE_URL = `${API_URL}/vacancies/{{ vacancyId }}/candidates/{{ candidateId }}`
export const TRANSFER_CANDIDATE_URL = `${API_URL}/vacancies/{{ vacancyId }}/candidates/transfer`
export const EMAIL_NOTIFICATION = `${API_URL}/send_resume_letters`
export const VACANCY_CHANGE_STATE_URL = `${VACANCY_URL}/change_state/{{ state }}`
export const DEPARTMENTS_TREE_URL = `${API_URL}/departments/tree`
export const DEPARTMENTS_URL = `${API_URL}/departments`
export const SERVICES_URL = `${API_URL}/services`
export const SERVICE_URL = `${API_URL}/services/{{ id }}`
export const BIDS_URL = `${API_URL}/bids`
export const BIDS_AUTHOR_URL = `${BIDS_URL}/author`
export const BIDS_EXECUTOR_URL = `${BIDS_URL}/executor`
export const BID_URL = `${BIDS_URL}/{{ id }}`
export const BID_STATES_URL = `${BIDS_URL}/{{ id }}/states`
export const BID_ALLOWED_STATES_URL = `${BIDS_URL}/{{ id }}/allowed_states`
export const BID_CHANGE_STATE_URL = `${BIDS_URL}/{{ id }}/change_state/{{ state }}`
export const BID_STB_PARTICIPANTS_STATE_URL = `${BIDS_URL}/{{ id }}/team_building_information_accounts`
export const CUSTOMERS_URL = `${API_URL}/customers`
export const CUSTOMERS_CONTACTS_URL = `${API_URL}/customers/{{ customerId }}/contacts`
export const CUSTOMERS_CONTACT_URL = `${API_URL}/customers/{{ customerId }}/contacts/{{ id }}`
export const COMMENT_CUSTOMERS_CONTACT_URL = `${API_URL}/customers/{{ customerId }}/contacts/{{ id }}/add_comment`
export const LEGAL_UNITS_URL = `${API_URL}/legal_units`
export const LEGAL_UNITS_DICTIONARY_URL = `${API_URL}/legal_units/dictionary`
export const PROJECTS_URL = `${API_URL}/projects`
export const PROJECTS_DICRTIONARY_URL = `${API_URL}/dictionaries/tag?entity=project`
export const PROJECT_URL = `${PROJECTS_URL}/{{ id }}`
export const PROFILES_PROJECT_URL = `${PROJECTS_URL}/{{ id }}/account_projects`
export const PROFILE_PROJECT_URL = `${PROJECTS_URL}/{{ id }}/account_projects/{{project_id}}`
export const FEEDS_URL = `${API_URL}/feed`
export const USERS_COUNTER_URL = `${API_URL}/visits/stats`
export const DISTRIBUTIONS_URL = `${API_URL}/mailing_lists`
export const DISTRIBUTION_URL = `${API_URL}/mailing_lists/{{ id }}`
export const COMPARISON_SAVE_BOTH = `${API_URL}/save_both`
export const COMPARISON_SAVE_ONE = `${API_URL}/save_one`
export const TASKS_URL = `${API_URL}/tasks`
export const TASK_URL = `${API_URL}/tasks/{{ id }}`
export const SUBTASKS_URL = `${API_URL}/tasks/{{ task_id }}/subtasks`
export const SUBTASK_URL = `${API_URL}/tasks/{{ task_id }}/subtasks/{{ id }}`
export const UPDATE_PASSWORD_URL = `${ACCOUNTS_URL}/update_password`
export const VACANCY_STAGES_GROUPS = `${API_URL}/vacancy_stage_groups/stats`
export const FILTERED_ANALYTICS_STAGES_GROUPS = `${API_URL}/vacancy_stage_groups/recruitment_vortex`
export const PROFILE_HR_URL = `${ACCOUNTS_URL}/{{ id }}?hr=true`
export const DISCUSSIONABLE_URL = `discussions`
export const DISCUSSIONS_URL = `${API_URL}/${DISCUSSIONABLE_URL}`
export const DISCUSSION_URL = `${API_URL}/${DISCUSSIONABLE_URL}/{{ id }}`
export const CANDIDATE_RATINGS_URL = `${API_URL}/candidate_ratings`
export const ASSESSMENT_SESSIONS_URL = `${API_URL}/assessment/sessions`
export const ASSESSMENT_SESSION_URL = `${API_URL}/assessment/sessions/{{id}}`
export const EVALUATIONS_ASSESSMENT_SESSION_URL = `${API_URL}/assessment/sessions/{{id}}/evaluations`
export const ASSESSMENT_SESSION_RESULT_URL = `${API_URL}/assessment/sessions/{{id}}/result`

export const AUTH_URL = '/auth'
export const RESET_NEW_PASSWORD_URL = `${AUTH_URL}/reset_password`
export const GENERATE_NEW_PASSWORD_URL = `${AUTH_URL}/generate_new_password_email`
export const SIGN_IN_URL = `${AUTH_URL}/signin`
export const LOGOUT_URL = `${AUTH_URL}/logout`

// ui
export const LOGGIN_SETTINGS_URL = `${AUTH_URL}/login_settings`
